services:
  - type: web
    name: proctorclay-ai-server
    plan: starter
    rootDir: ai_backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: YOLO_VERBOSE
        value: "false"
      - key: CORS_ORIGIN
        value: https://embedded-system-project.vercel.app
    region: oregon
